version: '3.3'

services:
  samba:
    container_name: samba
    image: hairokuma/samba
    build: .
    volumes:
      - '/path/to/share:/home/user'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped